site_name: Oppkey RICOH Viewer Demo Community Site
# change to theta360developers before official publication
site_url: https://codetricity.github.io/viewer-demo-docs
theme:
  name: material
  # features:
  #   - navigation.instant
repo_name: git@github.com:codetricity/viewer-demo-docs.git

