site_name: Oppkey RICOH Viewer Demo Community Site
# change to theta360developers before official publication
site_url: https://codetricity.github.io/ricoh-viewer
site_author: Oppkey

theme:
  name: material
  # features:
  #   - navigation.instant
  logo: images/oppkey_logo.jpg
  favicon: images/oppkey_logo.jpg
repo_name: git@github.com:codetricity/ricoh-viewer.git

nav:
  - Home: index.md
  - Cloud: cloud.md
  - Features: features.md
  - Contact: contact.md

